In [ ]:
import os
import sys
sys.path.insert(0, '/nfs/nfs2/users/riadoshi/bigvision_palivla')
sys.path.insert(0, '/nfs/nfs2/users/riadoshi/bigvision_palivla/dlimp')
sys.path.insert(0, '/nfs/nfs2/users/riadoshi/bigvision_palivla/octo')

import tensorflow as tf
from ml_collections import config_flags
from absl import flags

from palivla.dataset import make_base_dataset

# Turn off debug logs
tf.get_logger().setLevel("WARNING")

# Initialize flags
config_flags.DEFINE_config_file(
    "config", "/nfs/nfs2/users/riadoshi/bigvision_palivla/configs/one_action_rest_reasonings/sanity.py", "Path to the config file."
)

# Parse flags - removing problematic flags
flags_list = ["notebook", 
              "--config=/nfs/nfs2/users/riadoshi/bigvision_palivla/configs/one_action_rest_reasonings/sanity.py",
              "--config.dataset_kwargs.oxe_kwargs.data_dir=gs://rail-orca-central2/resize_256_256",
              "--config.dataset_kwargs.shuffle_buffer_size=100"]

try:
    argv = flags.FLAGS(flags_list)
    config = flags.FLAGS.config
    
    # Create the dataset
    train_ds = make_base_dataset(**config.dataset_kwargs.to_dict(), train=True)
    
except Exception as e:
    print(f"Error during flag parsing: {e}")
    # Fallback to direct config loading without flags
    from importlib.machinery import SourceFileLoader
    config_module = SourceFileLoader("config", "/nfs/nfs2/users/riadoshi/bigvision_palivla/configs/one_action_rest_reasonings/sanity.py").load_module()
    config = config_module.get_config()
    
    # Update config with necessary values
    config.dataset_kwargs.oxe_kwargs.data_dir = "gs://rail-orca-central2/resize_256_256"
    # config.cot_path = "gs://multi-robot-bucket3/data/generated_data"
    config.dataset_kwargs.shuffle_buffer_size = 100
    
    # Create the dataset
    train_ds = make_base_dataset(**config.dataset_kwargs.to_dict(), train=True)

2025-04-15 18:14:20.943706: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-04-15 18:14:20.947148: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-04-15 18:14:20.958486: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1744740860.977717  636660 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1744740860.983603  636660 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1744740860.997840  636660 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linkin

Error during flag parsing: Unknown command line flag 'config.dataset_kwargs.oxe_kwargs.data_dir'
getting dataset sizes


2025-04-15 18:14:28.016415: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


AttributeError: module 'ml_dtypes' has no attribute 'float4_e2m1fn'
Cause: Unable to locate the source code of <function _gcd_import at 0x7f765a967d80>. Note that functions defined in certain environments, like the interactive Python shell, do not expose their source code. If that is the case, you should define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.experimental.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Cause: Unable to locate the source code of <function _gcd_import at 0x7f765a967d80>. Note that functions defined in certain environments, like the interactive Python shell, do not expose their source code. If that is the case, you should define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.experimental.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Cause: Unable to locate the source code of <function _gcd_import at 0x7f765a967d80>. Note that functions defined in certain environments, like the interactive Python shell, do not expose their source code. If that is the case, you should define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.experimental.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


done getting dataset sizes

######################################################################################
# Loading the following 1 datasets (incl. sampling weight):                         #
# aloha_pick_place_full_dataset: ===========================================1.000000 #
######################################################################################

shuffling!


In [2]:
iter2 = iter(train_ds.batch(1))
bb = next(iter2)

2025-04-15 18:14:35.064195: I tensorflow/core/kernels/data/tf_record_dataset_op.cc:387] The default buffer size is 262144, which is overridden by the user specified `buffer_size` of 8388608


In [10]:
for i in range(30):
    bb = next(iter2)
    print(f"traj {i}")
    # print(bb['task']['language_instruction'][0])
    # print(bb['dataset_name'])
    # print(bb['observation']['pad_mask_dict'])
    # print(bb['observation']['proprio_bimanual'])
    print(bb['action'])
    

traj 0
tf.Tensor(
[[[[-0.2929946   0.04620651 -0.331346    0.75320077 -0.30377117
     1.4624164  -0.04397516  0.44921735 -1.6317309   1.1436974
     0.24820931 -0.82028115 -0.33895773  0.03723554]
   [-0.2929946   0.04620651 -0.2950151   0.7144335  -0.28680927
     1.4624164  -0.03495172  0.46443644 -1.588464    1.1362156
     0.28559858 -0.82028115 -0.3097517   0.03723554]
   [-0.3216862   0.04620651 -0.2586842   0.7144335  -0.26984704
     1.4624164  -0.02953779  0.5024841  -1.5488025   1.1324747
     0.32298782 -0.82028115 -0.2763734   0.03904023]
   [-0.3216862   0.04620651 -0.22235325  0.7144335  -0.25288478
     1.4624164  -0.02412372  0.53292227 -1.5055356   1.1249928
     0.35503578 -0.8158086  -0.23882277  0.03904023]
   [-0.3216862   0.04620651 -0.18602233  0.7144335  -0.23592253
     1.4624164  -0.02051435  0.586189   -1.4622685   1.117511
     0.38708374 -0.811336   -0.20544446  0.0426496 ]
   [-0.3216862   0.04620651 -0.11336049  0.7144335  -0.23592253
     1.4624164  -0.

In [11]:
action = bb['action'].numpy()[0, 0, :, :]
action

array([[-0.5512198 ,  0.3395599 , -1.2759471 , -0.06091154,  1.0871288 ,
         0.15238401,  0.07332917, -0.1899834 , -1.6858147 ,  1.1399565 ,
         0.851779  , -0.30146295, -0.2680288 ,  0.09498543],
       [-0.46514478,  0.38146752, -1.312278  , -0.06091154,  1.1719396 ,
         0.15238401,  0.07332917, -0.25085968, -1.6677868 ,  1.1362156 ,
         0.9212162 , -0.24779212, -0.23882277,  0.10039949],
       [-0.35037792,  0.3395599 , -1.2759471 , -0.06091154,  1.2397884 ,
         0.15238401,  0.07332917, -0.31934544, -1.6461532 ,  1.1324747 ,
         1.0013361 , -0.19412126, -0.20961674,  0.10942294],
       [-0.23561116,  0.38146752, -1.2759471 , -0.06091154,  1.3415616 ,
         0.15238401,  0.07332917, -0.38022172, -1.6317309 ,  1.1324747 ,
         1.065432  , -0.144923  , -0.18041073,  0.11844624],
       [-0.14953609,  0.38146752, -1.2759471 , -0.06091154,  1.4263725 ,
         0.15238401,  0.07332917, -0.44109794, -1.6173087 ,  1.1324747 ,
         1.1295279 , -0.08

In [ ]:
import mediapy
mediapy.show_image(bb['observation']['image_primary'].numpy().squeeze())

""


In [17]:
action = bb['action'].numpy()[0, 0, :, :]
import numpy as np
np.save('/nfs/nfs2/users/riadoshi/bigvision_palivla/test_ac.npy', action)

In [4]:
sample_batch['reasonings'][0]

<tf.Tensor: shape=(), dtype=string, numpy=b'right-end-effector<loc0199><loc0619>;white bowl 1<loc0489><loc0553><loc0562><loc0645>;right-end-effector<loc0281><loc0699>;right-end-effector<loc0391><loc0677>;right-end-effector<loc0457><loc0656>;right-end-effector<loc0485><loc0651>;white bowl 1<loc0521><loc0553><loc0562><loc0645>;'>