In [1]:
import numpy as np
import os
import matplotlib.pyplot as plt 
from PIL import Image
import io
# !pip install mediapy
import mediapy

In [2]:
PATH = "/nfs/nfs2/users/riadoshi/eval_logs/041025-05:07"

In [3]:
image_files = os.listdir(f"{PATH}/images/")
image_files.sort(key=lambda x: int(x[x.index('_')+1 : x.index('.')]))

images = []
for file in image_files:
    pil_img  = Image.open(f"{PATH}/images/{file}")
    images.append(np.array(pil_img))

In [4]:
info = np.load(f'{PATH}/info.npy', allow_pickle=True).item()
actions, cots = info['actions'], info['cots']
actions

[array([-0.00112334,  0.00014206,  0.0019951 ,  0.01120939, -0.00095348,
        -0.01461489,  0.        ]),
 array([-0.00734571,  0.00526705, -0.01302148,  0.00763913,  0.05250809,
        -0.00590631,  0.        ]),
 array([ 0.00110347, -0.0053294 ,  0.00400666,  0.00113253, -0.01143074,
        -0.01461489,  0.        ]),
 array([-0.00301114, -0.01717171, -0.00465025, -0.00275019, -0.01318806,
        -0.05663995,  0.        ]),
 array([-0.00500286, -0.02      , -0.00522555,  0.01573485,  0.01338408,
        -0.0373715 ,  0.        ]),
 array([-0.01311302, -0.0199633 , -0.01302148,  0.00505064,  0.0067482 ,
        -0.07848276,  0.        ]),
 array([-0.00534187, -0.00454594, -0.01547336,  0.02551682,  0.00604721,
        -0.0373715 ,  0.        ]),
 array([-0.01455788, -0.01171722, -0.01344216,  0.00730007,  0.01647695,
        -0.02250503,  0.        ]),
 array([ 0.02      ,  0.00884631, -0.01704462, -0.01283584, -0.03238527,
        -0.01461489,  0.        ]),
 array([-0.00156628

In [5]:
from palivla.visualizations.chain_of_thought import parse_cot_string, visualize_trajectory, TrajectoryData

def create_viz(
    image: np.ndarray,
    pred_trajectory: TrajectoryData,
    prompt_str: str,
) -> np.ndarray:
    """Create a side-by-side visualization comparing predicted and target trajectories.

    Args:
        image: Input image to show in both panels
        pred_trajectory: Predicted trajectory from the model
        target_trajectory: Target/ground truth trajectory
        prompt_str: Text prompt to show as subtitle

    Returns:
        PIL Image containing the rendered figure
    """
    # Create figure with two subplots side by side
    fig, (ax1) = plt.subplots(1, 1, figsize=(6, 6))

    # Remove <pad> from prompt string
    fig.suptitle(prompt_str, wrap=True)

    # Plot predicted and target trajectories
    visualize_trajectory(ax1, image, pred_trajectory, "Predicted")

    # Adjust layout and convert to image
    plt.tight_layout()

    # Convert figure to PIL Image
    buf = io.BytesIO()
    plt.savefig(buf, format="png")
    buf.seek(0)
    img = Image.open(buf)
    plt.close(fig)

    return img

comp_imgs = []
for image, cot in zip(images, cots):
    pred_trajectory_data = parse_cot_string(cot)
    comparison_image = create_viz(
        image, pred_trajectory_data, "put mushroom in pot"
    )
    comp_imgs.append(np.array(comparison_image)[:,:,:3])
mediapy.show_video(comp_imgs, fps=1)


2025-04-11 21:05:53.842560: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1744405553.861274  269257 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1744405553.867018  269257 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1744405553.880505  269257 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1744405553.880524  269257 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1744405553.880526  269257 computation_placer.cc:177] computation placer alr

(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)


In [22]:
mediapy.show_video(comp_imgs, fps=1)

In [ ]:
# i also want to visualize how the CoT looks.... but that prob won't be too much of an indication of anything
for cot in 