In [1]:
import numpy as np
import os
import matplotlib.pyplot as plt 
from PIL import Image
import io
# !pip install mediapy
import mediapy

In [2]:
PATH = "/nfs/nfs2/users/riadoshi/eval_logs/042325-17:35"

In [3]:
image_files = os.listdir(f"{PATH}/images/")
image_files.sort(key=lambda x: int(x[x.index('_')+1 : x.index('.')]))

images = []
for file in image_files:
    pil_img  = Image.open(f"{PATH}/images/{file}")
    images.append(np.array(pil_img))

In [4]:
info = np.load(f'{PATH}/info.npy', allow_pickle=True).item()
actions, cots = info['actions'], info['cots']
actions

[array([ 0.01932762, -0.02      ,  0.00731952, -0.05043987, -0.03586185,
        -0.03828531,  0.        ]),
 array([-0.00455992, -0.00173738, -0.01474736, -0.02062789,  0.03678746,
        -0.05223798,  0.        ]),
 array([-1.03393470e-02, -3.77945538e-03,  5.30795801e-03, -4.65380851e-04,
        -5.49584567e-03,  5.09852166e-02,  1.05000000e+00]),
 array([ 2.00000000e-02, -2.00000000e-02,  4.60549506e-03, -4.88331658e-02,
         2.06069914e-02, -5.66858894e-04,  1.05000000e+00]),
 array([-0.0117842 ,  0.01103405,  0.02      ,  0.0021231 ,  0.01787892,
        -0.04526164,  0.        ]),
 array([-0.00610871, -0.00344996, -0.01704462,  0.02711474,  0.06117105,
        -0.01461489,  1.05      ]),
 array([0.01534718, 0.02      , 0.01109233, 0.02773989, 0.00322409,
        0.01952003, 1.05      ]),
 array([-2.25353203e-04, -1.56005743e-02, -8.82800438e-03, -6.60415374e-02,
        -2.57493846e-02,  2.30081930e-02,  1.05000000e+00]),
 array([ 0.00021759,  0.00012508, -0.00017108, -0.0

In [5]:
mediapy.show_video(images, fps=2)

In [5]:
from palivla.visualizations.chain_of_thought import parse_cot_string, visualize_trajectory, TrajectoryData

def create_viz(
    image: np.ndarray,
    pred_trajectory: TrajectoryData,
    prompt_str: str,
) -> np.ndarray:
    """Create a side-by-side visualization comparing predicted and target trajectories.

    Args:
        image: Input image to show in both panels
        pred_trajectory: Predicted trajectory from the model
        target_trajectory: Target/ground truth trajectory
        prompt_str: Text prompt to show as subtitle

    Returns:
        PIL Image containing the rendered figure
    """
    # Create figure with two subplots side by side
    fig, (ax1) = plt.subplots(1, 1, figsize=(6, 6))

    # Remove <pad> from prompt string
    fig.suptitle(prompt_str, wrap=True)

    # Plot predicted and target trajectories
    visualize_trajectory(ax1, image, pred_trajectory, "Predicted")

    # Adjust layout and convert to image
    plt.tight_layout()

    # Convert figure to PIL Image
    buf = io.BytesIO()
    plt.savefig(buf, format="png")
    buf.seek(0)
    img = Image.open(buf)
    plt.close(fig)

    return img

comp_imgs = []
for image, cot in zip(images, cots):
    pred_trajectory_data = parse_cot_string(cot)
    comparison_image = create_viz(
        image, pred_trajectory_data, "put mushroom on top of the pot"
    )
    comp_imgs.append(np.array(comparison_image)[:,:,:3])
mediapy.show_video(comp_imgs, fps=1)


2025-04-22 18:42:00.682530: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1745347320.701092  906326 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1745347320.706784  906326 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1745347320.720623  906326 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1745347320.720640  906326 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1745347320.720642  906326 computation_placer.cc:177] computation placer alr

(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)


In [16]:
mediapy.show_video(comp_imgs, fps=1)


In [6]:
!sudo apt install ffmpeg -y

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libatasmart4 libblockdev-fs2 libblockdev-loop2 libblockdev-part-err2
  libblockdev-part2 libblockdev-swap2 libblockdev-utils2 libblockdev2
  libmm-glib0 libnspr4 libnss3 libparted-fs-resize0 libudisks2-0
  usb-modeswitch usb-modeswitch-data
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  i965-va-driver intel-media-va-driver libaacs0 libaom0 libass9 libasyncns0
  libavc1394-0 libavcodec58 libavdevice58 libavfilter7 libavformat58
  libavresample4 libavutil56 libbdplus0 libbluray2 libbs2b0 libcaca0
  libcairo-gobject2 libcdio-cdda2 libcdio-paranoia2 libcdio18 libchromaprint1
  libcodec2-0.9 libdc1394-22 libdrm-amdgpu1 libdrm-intel1 libdrm-nouveau2
  libdrm-radeon1 libfftw3-double3 libflac8 libflite1 libgdk-pixbuf2.0-0
  libgdk-pixbuf2.0-bin libgdk-pixbuf2.0-common l